apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/db
    type: DirectoryOrCreate
