apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "backend.name" . }}
  ports:
  - port: 8080
    targetPort: 8080

