apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
spec:
  serviceName: {{ include "db.fullname" . }}
  replicas: {{ .Values.replicaCount | default $.Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ include "db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db.name" . }}
    spec:
      containers:
      - name: db
        image: "{{ .Values.image.repository | default $.Values.db.image.repository }}:{{ .Values.image.tag | default $.Values.db.image.tag }}"
        ports:
        - containerPort: 5432
        {{- if or .Values.persistence.enabled $.Values.db.persistence }}
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        {{- end }}
  {{- if or .Values.persistence.enabled $.Values.db.persistence }}
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.persistence.storage | default $.Values.db.storage }}
  {{- else }}
  template:
    spec:
      volumes:
      - name: db-storage
        emptyDir: {}
  {{- end }}

