apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-db
spec:
  serviceName: todo-app-db
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
      - name: db
        image: postgres:latest
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        emptyDir: {}

