apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-db
spec:
  serviceName: todo-app-db
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
      - name: db
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "todo"
        - name: POSTGRES_PASSWORD
          value: "todo123"
        - name: POSTGRES_DB
          value: "tododb"
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
          subPath: data   # 👈 Fix: mount into subdirectory
      volumes:
      - name: db-storage
        emptyDir: {}       # 👈 ephemeral storage (not PV/PVC)

