apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    app: {{ include "db.name" . }}
spec:
  serviceName: {{ include "db.fullname" . }}
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ include "db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "db.name" . }}
    spec:
      containers:
      - name: db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: {{ .Values.db.resources.requests.cpu }}
            memory: {{ .Values.db.resources.requests.memory }}
          limits:
            cpu: {{ .Values.db.resources.limits.cpu }}
            memory: {{ .Values.db.resources.limits.memory }}
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
{{- if not .Values.db.persistence.enabled }}
      volumes:
      - name: db-storage
        emptyDir: {}
{{- end }}

{{- if .Values.db.persistence.enabled }}
volumeClaimTemplates:
- metadata:
    name: db-storage
  spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
{{- end }}

